export const lifecycleStages = [
  {
    id: "intent",
    label: "Intent",
    detail: "Human purpose, outcomes, constraints, policy, risk, and acceptance expectations.",
    canonical: "Intent",
    concepts: ["Human intent", "Strategy", "Policy", "Risk", "Acceptance"],
  },
  {
    id: "plan",
    label: "Plan",
    detail: "Decomposition, executable specifications, contracts, authority, and acceptance criteria.",
    canonical: "Plan",
    concepts: ["Decomposition", "Specifications", "Contracts", "Authority", "Scope"],
  },
  {
    id: "execute",
    label: "Execute",
    detail: "Define agents, run through harnesses, apply skills, manage context, environments, and compute.",
    canonical: "Define Agent → Execute through Harness → Apply Skills",
    concepts: ["Agents", "Harnesses", "Skills", "Tools", "Runtime"],
  },
  {
    id: "verify",
    label: "Verify",
    detail: "Evaluate exact candidates through independent checks, evidence, provenance, and proof packages.",
    canonical: "Evaluate",
    concepts: ["Tests", "Evals", "Verification", "Evidence", "Provenance"],
  },
  {
    id: "deliver",
    label: "Deliver",
    detail: "Decision gates, merge, release, progressive deployment, production checks, and rollback.",
    canonical: "Deliver Software",
    concepts: ["Decision gates", "CI/CD", "Release", "Production", "Rollback"],
  },
  {
    id: "learn",
    label: "Learn",
    detail: "Observe outcomes, analyze failures, compare candidates, and govern improvements.",
    canonical: "Improve",
    concepts: ["Observability", "Feedback", "Replay", "Improvement", "Promotion"],
  },
] as const;

export type LifecycleStageId = (typeof lifecycleStages)[number]["id"];

export const learningPathBlueprints = [
  {
    id: "executive",
    number: "01",
    title: "Executive",
    goal: "Understand",
    depth: "Light",
    audience: "Engineering and business leaders",
    time: "~45 min",
    outcome: "Explain value, risk, governance, and accountable autonomy.",
    instruction: "Use each chapter’s existing Quick Read to build a precise executive narrative.",
    slugs: [
      "00-overview/01-ai-software-factory-and-mission-control",
      "01-vision/01-what-is-an-ai-software-factory",
      "03-operating-model/01-human-agent-operating-model",
      "02-first-principles/01-operational-autonomy-and-trust-calibration",
      "07-quality-engineering/01-quality-and-evidence-architecture",
      "00-overview/08-capability-coverage-and-maturity",
    ],
  },
  {
    id: "architect",
    number: "02",
    title: "Architect",
    goal: "Design",
    depth: "Medium",
    audience: "Architects and senior technical leaders",
    time: "~6 hours",
    outcome: "Whiteboard the complete system and defend every boundary and contract.",
    instruction: "Trace authority downward, evidence upward, and recovery across every state boundary.",
    slugs: [
      "00-overview/11-detailed-architecture-coverage-matrix",
      "00-overview/05-software-factory-stack-boundaries",
      "00-overview/04-intent-to-delivery-lifecycle",
      "04-domain-model/01-authoritative-delivery-hierarchy",
      "05-runtime-architecture/01-control-plane-and-execution-plane",
      "05-runtime-architecture/02-runtime-orchestration-and-state-machines",
      "05-runtime-architecture/09-orchestration-component-model-and-runtime-contracts",
      "05-runtime-architecture/07-development-environments-compute-and-composable-infrastructure",
      "05-runtime-architecture/08-coding-harnesses-adapters-and-agent-protocols",
      "agent-factory/01-capability-supply-chain-and-registries",
      "agent-factory/04-tool-skill-and-integration-contract-reference",
      "06-ai-engineering/08-knowledge-context-and-retrieval-pipeline-specification",
      "07-quality-engineering/01-quality-and-evidence-architecture",
      "verification-delivery-engineering/02-cicd-artifacts-migrations-and-api-compatibility",
      "08-security-and-governance/04-agentic-threat-model-and-adversarial-defense",
      "08-security-and-governance/06-agentic-governance-control-framework",
      "factory-platform-engineering/07-enterprise-operations-reliability-and-finops-reference",
    ],
  },
  {
    id: "builder",
    number: "03",
    title: "Builder",
    goal: "Implement",
    depth: "Deep",
    audience: "Platform, AI, quality, and delivery engineers",
    time: "~12 hours",
    outcome: "Build and exercise a governed delivery path through failure and recovery.",
    instruction: "Complete the evidence, failure, rollback, learning, and cleanup paths—not only the happy path.",
    slugs: [
      "autonomous-workflows/01-repository-onboarding-and-codebase-intelligence",
      "agent-factory/01-capability-supply-chain-and-registries",
      "06-ai-engineering/01-agent-architecture-mcp-tools-context-and-memory",
      "06-ai-engineering/05-agent-and-loop-engineering-patterns",
      "06-ai-engineering/10-agentic-architecture-patterns-and-autonomy-selection",
      "05-runtime-architecture/03-tasks-attempts-leases-idempotency-and-recovery",
      "verification-delivery-engineering/01-software-testing-strategy-for-agentic-change",
      "06-ai-engineering/04-evaluation-engineering-trace-replay-and-run-comparison",
      "verification-delivery-engineering/03-progressive-delivery-production-verification-and-rollback",
      "10-labs/11-orchestration-failure-recovery-and-cost-lab",
      "10-labs/12-knowledge-poisoning-revocation-and-retrieval-lab",
      "10-labs/06-progressive-delivery-and-rollback-lab",
      "10-labs/08-continual-improvement-promotion-lab",
    ],
  },
  {
    id: "deep-study",
    number: "04",
    title: "Deep Study",
    goal: "Master the curriculum",
    depth: "Complete",
    audience: "Practitioners preparing to design, build, and defend the system",
    time: "Complete corpus",
    outcome: "Defend architecture and implementation decisions from first principles.",
    instruction: "Follow the complete corpus, then complete labs, case studies, and interview practice.",
    slugs: [] as string[],
  },
] as const;
