// Generated by scripts/sync-global-navigation.mjs from FDLC/lib/global-navigation.ts. Do not edit.
// Canonical FDLC global navigation. The Guide consumes a generated copy.
export type NavLink = readonly [label: string, href: string];

export const primary = [
  ["Framework", "/framework"],
  ["Architecture", "/architecture"],
] as const satisfies readonly NavLink[];

export const guide = [
  ["Overview", "/guide"],
  ["Atlas", "/guide/atlas"],
  ["Reference", "/guide/topics"],
  ["Glossary", "/guide/glossary"],
  ["Search", "/guide/search"],
] as const satisfies readonly NavLink[];

export const afterGuide = [
  ["Mission Control", "/mission-control"],
  ["FDE", "/deploy"],
  ["Maturity", "/maturity"],
] as const satisfies readonly NavLink[];

export const secondary = [
  ["FDLC in 5 Minutes", "/in-5-minutes"],
  ["Manifesto", "/manifesto"],
  ["Start", "/start"],
  ["Enterprise", "/enterprise"],
  ["About", "/about"],
] as const satisfies readonly NavLink[];

export const footerGroups = [
  ["Learn", [["Framework", "/framework"], ["Architecture", "/architecture"], ["Guide", "/guide"], ["Manifesto", "/manifesto"]]],
  ["Build", [["FDLC in 5 Minutes", "/in-5-minutes"], ["Mission Control", "/mission-control"], ["Specification", "/specification"], ["Start", "/start"], ["GitHub", "https://github.com/jaydubya818/MissionControl"]]],
  ["Adopt", [["Maturity", "/maturity"], ["Benchmarks", "/benchmarks"], ["Enterprise", "/enterprise"], ["FDE", "/deploy"]]],
  ["Project", [["About", "/about"], ["Source audit", "https://github.com/jaydubya818/ai-software-factory-mastery"], ["Mission Control status", "https://github.com/jaydubya818/MissionControl/blob/main/docs/product/software-factory-capability-maturity.md"]]],
] as const;
