export const guideParts = [
  {
    id: "understand",
    number: "01",
    verb: "Understand",
    title: "See the factory as a system",
    summary: "Establish the purpose, vocabulary, lifecycle, boundaries, and trust model before choosing tools or agents.",
    sectionKeys: ["00-overview", "01-vision", "02-first-principles"],
  },
  {
    id: "design",
    number: "02",
    verb: "Design",
    title: "Define ownership, records, and authority",
    summary: "Design the operating model, domain model, specifications, risk decisions, and control boundaries that make execution governable.",
    sectionKeys: ["03-operating-model", "04-domain-model"],
  },
  {
    id: "build",
    number: "03",
    verb: "Build",
    title: "Assemble the capability and execution stack",
    summary: "Build the Agent Factory, runtime, AI engineering layers, development environments, compute, and autonomous workflows.",
    sectionKeys: ["agent-factory", "05-runtime-architecture", "06-ai-engineering", "autonomous-workflows"],
  },
  {
    id: "prove",
    number: "04",
    verb: "Prove",
    title: "Verify, govern, and deliver exact outcomes",
    summary: "Create independent evidence, secure the supply chain, enforce decision rights, and move approved artifacts safely into production.",
    sectionKeys: ["verification-delivery-engineering", "07-quality-engineering", "08-security-and-governance"],
  },
  {
    id: "operate",
    number: "05",
    verb: "Operate",
    title: "Run the factory as a production platform",
    summary: "Operate portals, catalogs, workers, capacity, cost, telemetry, incident response, resilience, and human control surfaces.",
    sectionKeys: ["factory-platform-engineering"],
  },
  {
    id: "improve",
    number: "06",
    verb: "Improve",
    title: "Learn from evidence without self-authorizing change",
    summary: "Use versioned case studies, controlled practice, research, and clear explanation to improve the factory under human authority.",
    sectionKeys: ["09-mission-control-case-studies", "10-labs", "11-interview-mastery", "12-research-journal"],
  },
] as const;

export const sectionGuidance: Record<string, string> = {
  "00-overview": "Start with the complete system, canonical vocabulary, lifecycle, and boundary model.",
  "01-vision": "Understand what the factory changes—and what it does not replace.",
  "02-first-principles": "Calibrate trust, autonomy, evidence, and human authority from first principles.",
  "03-operating-model": "Define decision rights, economics, adoption, attention, and controlled improvement.",
  "04-domain-model": "Model the authoritative records that carry intent, scope, work, attempts, and outcomes.",
  "agent-factory": "Create and govern reusable agents, skills, tools, model profiles, and evaluation assets.",
  "05-runtime-architecture": "Build the control, execution, environment, compute, orchestration, and recovery substrate.",
  "06-ai-engineering": "Engineer data, knowledge, semantics, context, models, agents, loops, evaluation, and memory.",
  "autonomous-workflows": "Turn capabilities into bounded engineering workflows with explicit triggers and completion contracts.",
  "verification-delivery-engineering": "Test exact changes, preserve compatibility, release progressively, and prove production behavior.",
  "07-quality-engineering": "Turn observations into independent, current, attributable evidence and quality decisions.",
  "08-security-and-governance": "Protect identities, data, tools, supply chains, authority, and emergency controls.",
  "factory-platform-engineering": "Operate the factory as a reliable internal platform with capacity, cost, SLOs, and incident ownership.",
  "09-mission-control-case-studies": "Compare enduring architecture with a versioned control-plane implementation and its evidence boundaries.",
  "10-labs": "Exercise failure, recovery, security, delivery, and improvement paths against observable outcomes.",
  "11-interview-mastery": "Explain and defend the architecture, its tradeoffs, and its evidence boundaries to different audiences.",
  "12-research-journal": "Trace the source canon, open questions, and evolving conclusions behind the guide.",
};
