export const lifecycleStages = [
  {
    id: "intent",
    label: "Intent",
    detail: "Human purpose, outcomes, constraints, policy, risk, and acceptance expectations.",
    canonical: "Intent",
    slug: "01-builder-intent",
    concepts: ["Human intent", "Strategy", "Policy", "Risk", "Acceptance"],
  },
  {
    id: "plan",
    label: "Plan",
    detail: "Decomposition, executable specifications, contracts, authority, and acceptance criteria.",
    canonical: "Plan",
    slug: "02-plan",
    concepts: ["Decomposition", "Specifications", "Contracts", "Authority", "Scope"],
  },
  {
    id: "define-agent",
    label: "Define Agent",
    detail: "Bind eligible, versioned agents, models, skills, tools, context, budgets, and authority.",
    canonical: "Define Agent",
    slug: "03-define-agent",
    concepts: ["Agent Definition", "Model route", "Execution manifest", "Factory Version"],
  },
  {
    id: "execute-through-harness",
    label: "Execute through Harness",
    detail: "Run bounded work with durable state, scoped tools, budgets, stopping, and recovery.",
    canonical: "Execute through Harness",
    slug: "04-execute-through-harness",
    concepts: ["Harness", "Attempt", "Tools", "Runtime", "Candidate"],
  },
  {
    id: "apply-skills",
    label: "Apply Skills",
    detail: "Apply exact, evaluated organizational methods inside the governed execution loop.",
    canonical: "Apply Skills",
    slug: "05-apply-skills",
    concepts: ["Skills", "Capability registry", "Tool contract", "Skill binding"],
  },
  {
    id: "evaluate",
    label: "Evaluate",
    detail: "Evaluate exact Candidates through independent checks, evidence, provenance, and proof packages.",
    canonical: "Evaluate",
    slug: "06-evaluate",
    concepts: ["Tests", "Evals", "Verification", "Evidence", "Provenance"],
  },
  {
    id: "improve",
    label: "Improve",
    detail: "Observe outcomes, analyze failures, compare candidates, and govern improvements.",
    canonical: "Improve",
    slug: "07-improve",
    concepts: ["Observability", "Feedback", "Replay", "Improvement", "Promotion"],
  },
  {
    id: "deliver-software",
    label: "Deliver Software",
    detail: "Apply decision gates, merge, release, progressive deployment, production checks, and rollback.",
    canonical: "Deliver Software",
    slug: "08-deliver-software",
    concepts: ["Decision gates", "CI/CD", "Release", "Production", "Rollback"],
  },
] as const;

export type LifecycleStageId = (typeof lifecycleStages)[number]["id"];
